# Generated by Django 4.2.17 on 2025-01-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_thread_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
