# Generated by Django 4.2.17 on 2024-12-18 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100, verbose_name='Order')),
                ('family', models.CharField(max_length=100, verbose_name='Family')),
                ('genus', models.CharField(max_length=100, verbose_name='Genus')),
                ('scientific_name', models.CharField(max_length=100, unique=True, verbose_name='Scientific Name')),
                ('common_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Common Name')),
                ('subspecies', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subspecies')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
        ),
        migrations.CreateModel(
            name='SampleProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Provider Name')),
                ('short_name', models.CharField(max_length=10, unique=True, verbose_name='Short Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('provided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_providers', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10, unique=True, verbose_name='Unique Identifier')),
                ('name', models.CharField(max_length=100, verbose_name='Sample Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sample Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('number_of_samples', models.PositiveIntegerField(default=1, verbose_name='Number of Subsamples')),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Storage Location')),
                ('collection_date', models.DateField(blank=True, null=True, verbose_name='Collection Date')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_samples', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.project', verbose_name='Project')),
                ('sample_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.sampleprovider', verbose_name='Sample Provider')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.species', verbose_name='Species')),
            ],
        ),
    ]
