# Generated by Django 4.2.17 on 2024-12-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_storaging_remove_sample_storage_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='sampleprovider',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='sampleprovider',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='species',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='species',
            name='date_created',
        ),
    ]
