# Generated by Django 4.2.17 on 2024-12-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_remove_project_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
